### ISSUE TITLE
[BUG] Static pages

### ISSUE THREAD

**Issue by albert0vr** [juananmuxed/teamcoo#36]
**Describe the bug**
Static pages for Home-page, "Support CATAPA" (Previously called "members")

**To Reproduce**
1. Go to 'Portal Config' and General

**Expected behavior**
Find these two pages also editable.

**Comment by albert0vr** [comment]
"The registration page" also needs an editable section so we can adapt it when needed.

**Comment by juananmuxed** [comment]
This is a Feature too
