### ISSUE TITLE
[FEATURE] Static pages

### ISSUE THREAD

**Issue by albert0vr** [juananmuxed/teamcoo#38]
**Is your feature request related to a problem? Please describe.**
No way to edit static content at Home-page, registration page and "Support CATAPA" (Previously called "members")

**Describe the solution you'd like**
Static pages for Home-page, registration page and "Support CATAPA" (Previously called "members") with editable section so we can adapt it when needed.

**Additional context**
This is not a BUG.

**Comment by juananmuxed** [comment]
Expected to add a configuration in the backoffice to add Static Pages dinamically

**Comment by juananmuxed** [comment]
Added in #59
