### ISSUE TITLE
[FEATURE] TASKS get full and disappear from Open Tasks

### ISSUE THREAD

**Issue by albert0vr** [juananmuxed/teamcoo#91]
**Is your feature request related to a problem? Please describe.**
There is no way to know if tasks are already taken by the necessary amount of people.

**Describe the solution you'd like**
Tasks have amount of people indication (e.g.: 0/3, 2/3) and when the task is fully taken, it doesn't show up anymore in the dashboard of Open Tasks, but in the tasks taken by people "My Tasks" and in the Tasks list of the Working Group. Maybe visually shown with a shadowing.

**Describe alternatives you've considered**
Maybe instead of people amount, the task can have a management option to select that the task is already taken.

**Comment by juananmuxed** [comment]
Testing the webhooks
